### ISSUE TITLE
Admin site - manage jokes

### ISSUE THREAD

**Issue by LindaAPersson** [LindaAPersson/dadjokes#12]
As a Site Admin I can read, update and delete jokes to manage the site. 

### Acceptance criteria:

1. The admin can read a joke
2. The admin can update a joke
3. The admin can delete a joke

### Tasks:
- [x] Create functionality to read all jokes.
- [x] Create functionality to update all jokes.
- [x] Create functionality to delete all jokes.
- [ ] Ensure functionality is only accessible by admin.

### EPIC: #2
