### ISSUE TITLE
Jokes page - logged in user

### ISSUE THREAD

**Issue by LindaAPersson** [LindaAPersson/dadjokes#13]
As a logged in user, I can create, read, update, delete, comment and like jokes on the page to add to the sites content.

### Acceptance criteria:
1. The user can create a joke that is published when approved by admin 
2. The user can read all jokes.  
3. The user can update/edit their own joke, that is published when approved by admin 
4. The user can delete their own joke
5. The user can leave a comment on all the jokes, that is published when approved by admin  
6. The user can giva alla jokes a like if they want.  

### Tasks:
- [x] Create functionality to read all jokes.
- [x] Create functionality to create jokes.
- [x] Create functionality to update users jokes.
- [x] Create functionality to delete users jokes.
- [x] Create functionality to comment on all jokes.
- [x] Create functionality to leave a like on all jokes.
- [x] Ensure that the user can only update and delete their own jokes and comments.

### EPIC: #3
