### ISSUE TITLE
Jokes page - Guest user

### ISSUE THREAD

**Issue by LindaAPersson** [LindaAPersson/dadjokes#14]
As a site user, I can read all jokes to have a laugh.  

###Acceptance criteria:
1. When the site user open the jokes site, all the jokes are readable. 

### Tasks:
- [x] Connect the link to the jokes site correctly
- [x] Make sure all the jokes are readable.
- [x] Make sure the user do not have CRUD functionality

### EPIC: #4
