### ISSUE TITLE
Contact section - Admin

### ISSUE THREAD

**Issue by LindaAPersson** [LindaAPersson/dadjokes#17]
As a Site Admin, I can read the information that a user has put in the contact section to be able to respond. 

### Acceptance criteria:
1. The information put in the contact from is readable in the admin site.  

### Tasks:
- [x] Create a model for the contact section
- [x] Create a form and link it to the model
- [x] Create functionality to read all the information that the user put in the contact form.
- [x] Ensure it´s only the admin that can read all the information sent trough the contact form. 

### EPIC: #6
