### ISSUE TITLE
Contact section - Guest user

### ISSUE THREAD

**Issue by LindaAPersson** [LindaAPersson/dadjokes#18]
As a Site User, I can fill out the form in the contact section to get in touch with the developer/admin.

### Acceptance criteria:
1. The user can fill out the contact section and save the form. 

### Tasks:
- [x] Create functionality to write in the contact form.
- [x] Create a 'success message' when the form has been sent correctly
- [x] Create a 'error message' when the form has been sent correctly

### EPIC: #6
