### ISSUE TITLE
EPIC: Admin

### ISSUE THREAD

**Issue by LindaAPersson** [LindaAPersson/dadjokes#2]
As an Admin, I can manage the site's content to maintain the desired standard.

### User Stories:
- [x] Admin site - create jokes
- [x] Admin site - manage jokes
- [x] Admin site - manage user joke
- [x] Admin site - manage user comment
