### ISSUE TITLE
Registret - user

### ISSUE THREAD

**Issue by LindaAPersson** [LindaAPersson/dadjokes#21]
As a Site User I can register an account so I can involve with the jokes. 

### Acceptance criteria:
1.  Given an email a user can register an account.
2. Then the user can log in.
3. A warning message is given to display errors should an issue arise during registration 

### Tasks:
- [x] Create functionality for the user to register an account
- [x] Create a registration form
- [x] Create a button or link on the landing page to direct users to the registration page
- [x] Remove the sign-up button or link when the user is logged in and display a logout option

### EPIC: #4
