### ISSUE TITLE
Login - logout User

### ISSUE THREAD

**Issue by LindaAPersson** [LindaAPersson/dadjokes#22]
As a registered user on the site, I can login and logout to the site, to take part of all the site has to offer. 

### Acceptance criteria:
1. The user is rerouted to home page upon successful login and logout
2. UI updates to reflect logged-in/registierd status
3. A warning message is given to display errors should an issue arise during login/registration 
4. A notification askin if the user want to logout apers, that the user must accept before logout
5. A confirmation on successful logout  

### Tasks:
- [x] Create functionality for users to login and logout
- [x] Create login and logouts buttons
- [x] Create login and logout forms
- [x] Create message/text that shows if the user is logged in or logged out

### EPIC:  #3
