### ISSUE TITLE
EPIC: User - Logged in

### ISSUE THREAD

**Issue by LindaAPersson** [LindaAPersson/dadjokes#3]
As a user, I can share my content on the site to make it more personal.

### User Stories
- [x] Jokes page - logged in user
- [x] Home page - logged in user
- [x] About page - logged in user
