### ISSUE TITLE
EPIC: User - Not logged in

### ISSUE THREAD

**Issue by LindaAPersson** [LindaAPersson/dadjokes#4]
As a user who's not logged in, I can read the jokes and laugh.

### User Stories:
- [x] Home page - user not logged in
- [x] Jokes page - user not logged in
- [x] About page - user not logged in
- [x] Contact section - user not logged in
