### ISSUE TITLE
EPIC: HTML/CSS

### ISSUE THREAD

**Issue by LindaAPersson** [LindaAPersson/dadjokes#7]
As a developer I can create and style the pages to desired outcome

### User stories
- [x] Create the HTML and CSS for base.html
- [x] Create the HTML and CSS for home.html
- [x] Create the HTML and CSS for jokes.html
- [x] Create the HTML and CSS for about.html
