### ISSUE TITLE
Setup Django

### ISSUE THREAD

**Issue by LindaAPersson** [LindaAPersson/dadjokes#8]
As a developer I want to set up Django and install the initial supporting libraries needed so that I can begin development of the site

### Tasks
- [x] Install Django
- [x] Create and populate a requirements.txt and .gitnore file
- [x] Create a Django project
- [x] Create the first app needed and connect it in settings.py

### EPIC: #1
